apiVersion: v2

# We must to keep the name like this. IT is a OCI requirement for pushing OCI image (our chart)
# to the repository with a name like AWS ECR were named.
# HOW-TO: Push chart to a AWS ECR repo https://docs.aws.amazon.com/AmazonECR/latest/userguide/push-oci-artifact.html

name: filecoin-dev-apn1-glif-chart-external-snapshotter
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.

type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "6.0.1"
